external_projects:
    beads: ../../../beads/mayor/rig
issue-prefix: gt
sync:
    mode: dolt-native
sync-branch: beads-sync
types.custom: agent,role,rig,convoy,slot,queue,event,message,molecule,gate,merge-request
